setlist_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('setlist_tracker_app.urls')),
    path('users', include('users.urls')),
]

setlist_tracker_app/urls.py
"""Defines URL patterns for setlist_tracker_app."""

from django.urls import path

from . import views

app_name = 'setlist_tracker_app'
urlpatterns = [
    # Home page
    path('', views.home, name='home'),
    # View all songs
    path('songs/', views.songs, name='songs'),
    # View links for a specific song
    path('song/<int:song_id>/', views.song, name='song'),
    # create new song
    path('new_song/', views.new_song, name='new_song'),
    # delete existing song
    path('delete_song/<int:song_id>', views.delete_song, name='delete_song'),
    # create new song
    path('new_link/<int:song_id>/', views.new_link, name='new_link'),
    # delete existing link
    path('delete_link/<int:song_id>/<int:link_id>/', views.delete_link, name='delete_link'),
    # edit existing link
    path('edit_link/<int:link_id>/', views.edit_link, name='edit_link'),
    # practice space for django templates
    path('bootstrap5_practice/', views.bootstrap5_practice, name='bootstrap5_practice'),

]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

setlist_tracker_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Song(models.Model):
    """Represents a song that I know how to play, sort of"""
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    # chords = models.CharField(max_length=200)
    # lyrics = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} - {self.artist}"

class Link(models.Model):
    """Represents a helpful link to something about a song I know"""
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    url = models.URLField(max_length=200)
    PERFORMANCE = "P"
    TUTORIAL = "T" 
    # add a map from literall to string for pretty printing
    TYPE_MAP = {
        PERFORMANCE: "Performance",
        TUTORIAL: "Tutorial",
    }
    TYPE_CHOICES = [
        (PERFORMANCE, "Performance"),
        (TUTORIAL, "Tutorial"),
    ]
    link_type = models.CharField(
        max_length=2,
        choices=TYPE_CHOICES,
        default=PERFORMANCE,
    )
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.TYPE_MAP[self.link_type]}"

users/models.py
from django.db import models

# Create your models here.

setlist_tracker_app/forms.py
from django import forms

from .models import Song, Link

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['title', 'artist']
        labels = {'title': 'Title', 'artist': 'Artist'}

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['name', 'link_type', 'url']
        labels = {
            'name': 'Name',
            'link_type': 'Type',
            'url': 'URL'
        }

setlist_tracker_app/views.py
from django.shortcuts import render, redirect

from .models import Song, Link
from .forms import SongForm, LinkForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.
def home(request):
    """The home page for setlist tracker."""
    return render(request, 'setlist_tracker_app/home.html')


@login_required
def songs(request):
    """A users list of songs"""
    songs = Song.objects.filter(owner=request.user).order_by("title")
    context = {"songs": songs}
    return render(request, 'setlist_tracker_app/songs.html', context)


@login_required
def song(request, song_id):
    """See links for a single song"""
    song = Song.objects.get(id=song_id)
    # Make sure the topic belongs to the current user.
    if song.owner != request.user:
        raise Http404
    links = song.link_set.order_by("name")
    context = {'song': song, 'links': links}
    return render(request, 'setlist_tracker_app/song.html', context)


@login_required
def new_song(request):
    """Add a new song"""
    if request.method != 'POST':
        form = SongForm()
    else:
        form = SongForm(data=request.POST)
        if form.is_valid():
            new_song = form.save(commit=False)
            new_song.owner = request.user
            new_song.save()
            return redirect('setlist_tracker_app:songs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'setlist_tracker_app/new_song.html', context)


@login_required
def new_link(request, song_id):
    """Add a new link for a particular song"""
    song = Song.objects.get(id=song_id)

    if request.method != 'POST':
        form = LinkForm()
    else:
        form = LinkForm(data=request.POST)
        if form.is_valid():
            new_link = form.save(commit=False)
            new_link.song = song
            new_link.save()
            return redirect('setlist_tracker_app:song', song_id=song_id)  # how to redirect to song_id?

    # Display a blank or invalid form.
    context = {'song': song, 'form': form}
    return render(request, 'setlist_tracker_app/new_link.html', context)


@login_required
def edit_link(request, link_id):
    """Use to edit an existing link"""
    link = Link.objects.get(id=link_id)
    song = link.song

    # Make sure the topic belongs to the current user.
    if song.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = LinkForm(instance=link)
    else:
        form = LinkForm(instance=link, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('setlist_tracker_app:song', song_id=song.id)

    # Display a blank or invalid form.
    context = {'link': link, 'song': song, 'form': form}
    return render(request, 'setlist_tracker_app/edit_link.html', context)


@login_required
def delete_song(request, song_id):
    # delete the song
    Song.objects.get(id=song_id).delete()
    return redirect('setlist_tracker_app:songs')


@login_required
def delete_link(request, song_id, link_id):
    # delete the song
    Link.objects.get(id=link_id).delete()
    return redirect('setlist_tracker_app:song', song_id=song_id)

def bootstrap5_practice(request):
    # make fake data here to practice rendering in a template
    my_list = [1, 2, 3, 4, 5]

    # test song form
    if request.method != 'POST':
        song_form = SongForm()

    context = {"my_list": my_list, "song_form": song_form}
    return render(request, 'setlist_tracker_app/bootstrap5_practice.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != "POST":
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect("setlist_tracker_app:home")

    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

setlist_tracker_app/templates/setlist_tracker_app/base.html
{% load bootstrap5 %}


<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
       shrink-to-fit=no">
  <title>Setlist Tracker</title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}
  
</head>


<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'setlist_tracker_app:home' %}">
      Setlist Tracker</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>


    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'setlist_tracker_app:songs' %}">
            Songs</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text">Hello, {{ user.username }}.</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'setlist_tracker_app:bootstrap5_practice' %}">bootstrap5_practice</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

setlist_tracker_app/templates/setlist_tracker_app/base_legacy.html
<p>
  <a href="{% url 'setlist_tracker_app:home' %}">Home</a> -
  <a href="{% url 'setlist_tracker_app:songs' %}">Songs</a> -
  {% if user.is_authenticated %}
  Hello, {{ user.username }} -
  <a href="{% url 'users:logout' %}">Log out</a>
  {% else %}
  <a href="{% url 'users:login' %}">Log in</a> -
  <a href="{% url 'users:register' %}">Register</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

setlist_tracker_app/templates/setlist_tracker_app/bootstrap5_practice.html
{% load bootstrap5 %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
       shrink-to-fit=yes">
  <title>Practice Bootstrap HTML</title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>

<body>


  <!-- {% block content %}. -->

  <form action="{% url 'setlist_tracker_app:new_song' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form song_form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
    {% endbuttons %}
  </form>

  <!-- Space. -->

  <h1>List of items from context</h1>

  <ul>
    {% for number in my_list %}
    <li>
      <h3>
        <p>{{number}}</p>
      </h3>
    </li>
    {% endfor %}
  </ul>

  <!-- {% endblock content %}. -->

</body>

</html>

setlist_tracker_app/templates/setlist_tracker_app/edit_link.html
{% extends "setlist_tracker_app/base.html" %}

{% block content %}
<p>Edit link for {{song}}:</p>

<form action="{% url 'setlist_tracker_app:edit_link' link.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">Confirm Changes</button>
</form>

{% endblock content %}

setlist_tracker_app/templates/setlist_tracker_app/home.html
{% extends "setlist_tracker_app/base.html" %}

{% block page_header %}
<div class="jumbotron">
  <h1 class="display-3">Build your Setlist.</h1>

  <p class="lead">Keep track of your go to performance songs, or any songs youd like
    to learn and practice. Build lists of performances and tutorials for every song in your
    setlist.</p>

  <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

setlist_tracker_app/templates/setlist_tracker_app/home_legacy.html
{% extends "setlist_tracker_app/base.html" %}

{% block content %}
<p>Welcome to your setlist tracker! Add songs you can perform along with helpful links.</p>
{% endblock content %}

setlist_tracker_app/templates/setlist_tracker_app/new_link.html
{% extends "setlist_tracker_app/base.html" %}

{% block content %}
<p>Add a new link for {{song}}:</p>

<form action="{% url 'setlist_tracker_app:new_link' song.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">Add link</button>
</form>

{% endblock content %}

setlist_tracker_app/templates/setlist_tracker_app/new_song.html
{% extends "setlist_tracker_app/base.html" %}

{% block content %}
<p>Add a new song:</p>

<form action="{% url 'setlist_tracker_app:new_song' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">Add song</button>
</form>

{% endblock content %}

setlist_tracker_app/templates/setlist_tracker_app/song.html
{% extends "setlist_tracker_app/base.html" %}

{% block page_header %}
<h1>Your Songs</h1>
{% endblock page_header %}



{% block content %}
<p>{{song}}</p>

<ul>
  {% for link in links %}
  <li><h3>
    <p>{{link}}</p>
  </h3></li>
  <p>
    <a href="{{link.url}}" target="_blank">open</a>&ensp;---&ensp;
    <a href="{% url 'setlist_tracker_app:edit_link' link.id %}">edit</a>&ensp;---&ensp;
    <a href="{% url 'setlist_tracker_app:delete_link' song_id=song.id link_id=link.id %}">delete</a>
  </p>
  {% empty %}
  <li><h3>No links added yet.</h3></li>
  {% endfor %}
  <li><h3>
    <a href="{% url 'setlist_tracker_app:new_link' song.id %}">Add a new link</a>
  </h3></li>
</ul>

<h3><a href="{% url 'setlist_tracker_app:delete_song' song.id %}">Delete this song</a></h3>

{% endblock content %}

setlist_tracker_app/templates/setlist_tracker_app/songs.html
{% extends "setlist_tracker_app/base.html" %}

{% block content %}
<ul>
  {% for song in songs %}
  <li>
    <a href="{% url 'setlist_tracker_app:song' song.id %}">{{song}}</a>
  </li>
  {% empty %}
  <li>No songs added yet.</li>
  {% endfor %}
  <li>
    <a href="{% url 'setlist_tracker_app:new_song' %}">Add a new song</a>
  </li>
</ul>
{% endblock content %}